### ISSUE TITLE
Should run_experiment_G4_example.m work?  

### ISSUE THREAD

**Issue by leburnett** [JaneliaSciComp/G4_Display_Tools#110]
Should the file `\G4_Display_Tools\G4_Example_Experiment_Scripts\run_experiment_G4_example.m` work? 

I tried running it earlier but got the following error:
![image](https://github.com/JaneliaSciComp/G4_Display_Tools/assets/112313748/c259b664-11a4-4531-87b2-9b3b2dac39f9)

It appears that the folder `C:\matlabroot\G4\Experiments\` doesn't exist anymore. @floesche and I just pulled the newest code onto the computer so the files should be up to date.

**Comment by taylorlm88** [comment]
Probably not, it was created years ago. I can update it so it will work again, and get some improved examples.

**Comment by taylorlm88** [comment]
@leburnett FYI there is an example experiment at "G4_Display_Tools\G4_Protocol_Designer\test_protocols\test_protocol1" if you are looking for a sample experiment to run. I think the script 'run_experiment_G4_example.m' was created even before we used run protocols or anything.

**Comment by leburnett** [comment]
> @leburnett FYI there is an example experiment at "G4_Display_Tools\G4_Protocol_Designer\test_protocols\test_protocol1" if you are looking for a sample experiment to run. I think the script 'run_experiment_G4_example.m' was created even before we used run protocols or anything.

Thanks, @taylorlm88 I can give it a try and check that everything runs smoothly.

**Comment by taylorlm88** [comment]
@floesche @leburnett 

The files in G4_Example_Experiment_Scripts show how to create an experiment completely with scripts, bypassing the Designer and Conductor all together. They were written before we had the Designer and Conductor to create and run experiments. The file run_experiment_G4_example.m doesn't work until you use the file create_experiment_G4_example.m to create one. 

Do we want to keep these files? If we want these files to be available so users can see programmatically what goes into an experiment, or even so users can use them if they prefer programming to using the GUIs, I can update them so they will work again. But if we don't want users to have the option of creating and running experiments with these scripts, I can just remove them all together. 

What do you guys think?

**Comment by floesche** [comment]
How much effort would be required for updating them? 


I think there is a good use case for keeping them functional, but if it requires two weeks of work, that use case goes away.

**Comment by taylorlm88** [comment]
I've updated these scripts and they are working again. You have to run "create_experiment_G4_example.m" first, then "run_experiment_G4_example.m"

**Comment by taylorlm88** [comment]
The scripts work and i've updated the software setup documentation. commit d4647e2 and commit 4cdf910
