### ISSUE TITLE
Main Host application memory error

### ISSUE THREAD

**Issue by taylorlm88** [JaneliaSciComp/G4_Display_Tools#22]
If you try to send a command to the Main Host application via its Labview GUI before it has been connected with the command connectHost, it starts sending a slew of "out of memory" errors. This error window pops up over and over again, you might get a dozen or more before you manage to close the application. It'd be nice to have a better way of handling this if a user forgets to run the 'connectHost' command, like a single error message reminding them.

**Comment by floesche** [comment]
To replicate this error, start `G4 Host.exe`, then issue the command `Set Pattern ID` = 1. This leads to a quick increase of memory usage and the application crashes with an out of memory error within a few seconds.

The pattern can either be set via the GUI (see below) or via the TCP command [0x03 0x03 0x01 0x00].

![image](https://user-images.githubusercontent.com/1568893/156105041-4dd1260a-e05c-45be-bfd1-435daa2b28bd.png)

**Comment by floesche** [comment]
Sending a `Set Pattern and Position Function` with any number (eg `[1 1]`) also creates a similar memory issue.

![image](https://user-images.githubusercontent.com/1568893/156256455-5fb19eab-d29d-4217-a329-64971d12a487.png)

**Comment by floesche** [comment]
This is what `G4 Host.exe` reports:

![image](https://user-images.githubusercontent.com/1568893/156256533-52ba843f-c026-4bf6-a05e-10f8e670d80e.png)

**Comment by floesche** [comment]
This problem is fixed in v240
