### ISSUE TITLE
Experiment Length Calculator

### ISSUE THREAD

**Issue by taylorlm88** [JaneliaSciComp/G4_Display_Tools#25]
When you calculate the experiment length on the experiment Designer, two numbers pop up instead of one. On the Conductor, it always shows 15 seconds. Bugs probably introduced during other changes and never noticed.

**Comment by taylorlm88** [comment]
Fixed. However, there is a follow up issue where if the pre-trial is set to run until the user presses a button, its final length is not included in the experiment's total predicted length, and therefore the actual length of the experiment will be off by the length of the pre-trial. Will address this in the future.

**Comment by floesche** [comment]
Follow up is #45

**Comment by taylorlm88** [comment]
243b7b7e72873665c6acd8a86d1c5135002d72c2 - fix
