### ISSUE TITLE
closed loop experiment wont progress

### ISSUE THREAD

**Issue by gruyal** [JaneliaSciComp/G4_Display_Tools#4]
I ran a closed loop experiment that required a button press to progress. While the experiment was running, a closed figures that were open. As a result I could not cause the experiment to progress and had to restart.

This is the error that was reported on the main screen:

Error using waitforbuttonpress
waitforbuttonpress exit because target figure has been deleted

Error in G4_default_run_protocol (line 290)
                     w = waitforbuttonpress; %If pretrial duration is set to zero, this

Error in G4_conductor_controller/run (line 816)
            eval(run_command);

Error in G4_conductor_controller/run_test (line 1039)
                self.run();

Error in G4_conductor_view/run_test_exp (line 575)
            self.con.run_test();

Error in G4_conductor_view>@(varargin)self.run_test_exp(varargin{:}) (line 376)
                'units', 'pixels', 'Position', [210, 120, 150, 20], 'Callback', @self.run_test_exp);
 
Error while evaluating UIControl Callback.

**Comment by taylorlm88** [comment]
This functionality requires you to click on the conductor window. If it has been closed, it can no longer register the mouse click.
