### ISSUE TITLE
Function Generator: Cancel dialog shows wrong save directory

### ISSUE THREAD

**Issue by floesche** [JaneliaSciComp/G4_Display_Tools#43]
Cancel directory selection leads to displaying "0" as the directory, even though the internal setting seems correct.

![image](https://user-images.githubusercontent.com/1568893/145629998-7cecf2f2-692a-4ddc-92ee-4814dc64f1f6.png)

How to replicate: "Choose save directory", then click "Cancel". If the current function name doesn't exist yet, "save current function" still creates a valid function -- otherwise it creates an error.

**Comment by taylorlm88** [comment]
Fixed with commit ba743cbff67be8f43448d8454f0de4356da86ff7
