### ISSUE TITLE
Intertrial shows wrong pattern

### ISSUE THREAD

**Issue by floesche** [JaneliaSciComp/G4_Display_Tools#84]
On the `NewestVersion` branch (and probably the "Log Files Separately" run protocol, the intertrial shows the previous pattern instead of the intertrial pattern. The Pattern moves just before the next conditions starts.

(error copied from slack)

**Comment by floesche** [comment]
@SannaKoskela and @taylorlm88 , can you confirm this is a duplicate of #86 fixed by that solution?

**Comment by taylorlm88** [comment]
I haven’t tested the solution yet but it is the same issue. I was investigating #84 when I sent you the message in #86

**Comment by floesche** [comment]
Thanks. Closing this.
