### ISSUE TITLE
Error running `running posttrial`

### ISSUE THREAD

**Issue by floesche** [JaneliaSciComp/G4_Display_Tools#85]
On the master branch (with default run protocol) the Conductor gets stuck on "running posttrial":
```matlab
rror using movefile
The process cannot access the file because it is being used by another process.



Error in G4_conductor_controller/run (line 761)
            movefile(fullfile(experiment_folder,'Log Files','*'),fly_results_folder);

Error in G4_conductor_view/run_exp (line 619)
            self.con.run();

Error in G4_conductor_view>@(varargin)self.run_exp(varargin{:}) (line 139)
                'units', 'pixels', 'Position', [15, self.fig_size(4)- 305, 115, 85],'Callback', @self.run_exp);
 
Error while evaluating UIControl Callback.
```

The G4 Host shows this

![image](https://github.com/JaneliaSciComp/G4_Display_Tools/assets/1568893/37ef76bc-4863-4f98-b871-cf0b93898d57)

(error copied from Slack)

**Comment by taylorlm88** [comment]
Did we resolve this? It generally means the Log files are open elsewhere and so can't be moved to the experiment folder once the experiment is done running. I remember this happening on Sanna's computer but I think she figured out where the Log files were being accessed?
