### ISSUE TITLE
Error when running conductor without protocol

### ISSUE THREAD

**Issue by floesche** [JaneliaSciComp/G4_Display_Tools#90]
Opening the Conductor and clicking on the `Run` button produces this output:

![Annotation 2023-09-05 112608](https://github.com/JaneliaSciComp/G4_Display_Tools/assets/1568893/bf01cd0b-670c-4a11-b786-bde92453d048)

```matlab
>> G4_Experiment_Conductor
Warning: An empty directory name was given. No directory will be created.
This syntax may not be supported in future releases. 
> In G4_conductor_controller/run (line 539)
In G4_conductor_view/run_exp (line 602)
In G4_conductor_view>@(varargin)self.run_exp(varargin{:}) (line 140) 
Warning: An empty directory name was given. No directory will be created.
This syntax may not be supported in future releases. 
> In G4_conductor_controller/run (line 544)
In G4_conductor_view/run_exp (line 602)
In G4_conductor_view>@(varargin)self.run_exp(varargin{:}) (line 140) 
```

Possible solutions:

- Can the run button be disabled until an experiment is loaded? 
- Can the error message say something like "protocol not loaded yet" instead?

**Comment by taylorlm88** [comment]
Fixed with commit 20177ebaee688b6a22a5357cac9b3d3e0aa663c7
