### ISSUE TITLE
The "final comment" message looks unnecessarily like an error

### ISSUE THREAD

**Issue by floesche** [JaneliaSciComp/G4_Display_Tools#94]
This appears at the end of each experiment in the Conductor. It looks like an "Error message", but just asks for final comments.

![image](https://github.com/JaneliaSciComp/G4_Display_Tools/assets/1568893/edfa9722-c764-4fde-a877-e2ee889e0033)

Maybe the comments could be added within this dialog?

**Comment by taylorlm88** [comment]
Fixed with commit 108f092f217314db418370c6e8f9b66048ffabf9
